In [18]:
import tensorflow as tf
import pandas as pd
print(tf.__version__)

2.18.0


In [2]:
from tensorflow.keras.preprocessing.text import one_hot
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
        'your videos are good']

In [16]:
#ONE HOT ENCODING APPLIED

In [14]:
vocab_size=500
result_matrix=[]
for word in sent:
  print(f"{word}")
  result_matrix.append(one_hot(word,vocab_size))
  print(one_hot(word,vocab_size))
  print("   ")

the glass of milk
[366, 337, 158, 300]
   
the glass of juice
[366, 337, 158, 449]
   
the cup of tea
[366, 208, 158, 35]
   
I am a good boy
[112, 444, 211, 311, 192]
   
I am a good developer
[112, 444, 211, 311, 383]
   
understand the meaning of words
[8, 366, 362, 158, 196]
   
your videos are good
[218, 408, 255, 311]
   


In [15]:
# trying passing
result_matrix

[[366, 337, 158, 300],
 [366, 337, 158, 449],
 [366, 208, 158, 35],
 [112, 444, 211, 311, 192],
 [112, 444, 211, 311, 383],
 [8, 366, 362, 158, 196],
 [218, 408, 255, 311]]

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
# max sentences that are used in the sentences

arr=[]
def max_sent_size(sen):
  for x in result_matrix:

    arr.append((len(x)))
  return max(arr)
hightest_sent_word=max_sent_size(result_matrix[0])

In [24]:
# now APPLY THE PADDING TO EQUAL THE SIZE OF THE SENTNECES
sent_size=hightest_sent_word+3
embedded_docs=pad_sequences(result_matrix,maxlen=sent_size,padding='pre')

In [25]:
embedded_docs

array([[  0,   0,   0,   0, 366, 337, 158, 300],
       [  0,   0,   0,   0, 366, 337, 158, 449],
       [  0,   0,   0,   0, 366, 208, 158,  35],
       [  0,   0,   0, 112, 444, 211, 311, 192],
       [  0,   0,   0, 112, 444, 211, 311, 383],
       [  0,   0,   0,   8, 366, 362, 158, 196],
       [  0,   0,   0,   0, 218, 408, 255, 311]], dtype=int32)

## NOW APPLY THE EMBEDDING LAYER

In [27]:
# DIMENTIONS
dim=10
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_size))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [28]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
embedded_docs[0]

array([  0,   0,   0,   0, 366, 337, 158, 300], dtype=int32)

In [32]:
model.predict(embedded_docs[0]).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


(8, 10)

In [31]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step


array([[-0.00535621,  0.02441226,  0.03504497,  0.03434651, -0.01607971,
         0.04013875,  0.02607943, -0.04653217,  0.0307143 ,  0.04867481],
       [-0.00535621,  0.02441226,  0.03504497,  0.03434651, -0.01607971,
         0.04013875,  0.02607943, -0.04653217,  0.0307143 ,  0.04867481],
       [-0.00535621,  0.02441226,  0.03504497,  0.03434651, -0.01607971,
         0.04013875,  0.02607943, -0.04653217,  0.0307143 ,  0.04867481],
       [-0.00535621,  0.02441226,  0.03504497,  0.03434651, -0.01607971,
         0.04013875,  0.02607943, -0.04653217,  0.0307143 ,  0.04867481],
       [ 0.0045298 , -0.02498684,  0.01710642, -0.00817401, -0.02299626,
        -0.03960695,  0.03592752,  0.04486774, -0.01767631, -0.0391633 ],
       [-0.04834404,  0.02487589, -0.04648942, -0.04920632,  0.03282614,
        -0.04402144, -0.04964077, -0.04768776,  0.03593322,  0.03410617],
       [ 0.04050321, -0.02292818, -0.04965336, -0.04762937, -0.03717884,
         0.03386403,  0.00699116, -0.04110593

In [37]:
for x in embedded_docs:
  print(model.predict(x))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[-0.00535621  0.02441226  0.03504497  0.03434651 -0.01607971  0.04013875
   0.02607943 -0.04653217  0.0307143   0.04867481]
 [-0.00535621  0.02441226  0.03504497  0.03434651 -0.01607971  0.04013875
   0.02607943 -0.04653217  0.0307143   0.04867481]
 [-0.00535621  0.02441226  0.03504497  0.03434651 -0.01607971  0.04013875
   0.02607943 -0.04653217  0.0307143   0.04867481]
 [-0.00535621  0.02441226  0.03504497  0.03434651 -0.01607971  0.04013875
   0.02607943 -0.04653217  0.0307143   0.04867481]
 [ 0.0045298  -0.02498684  0.01710642 -0.00817401 -0.02299626 -0.03960695
   0.03592752  0.04486774 -0.01767631 -0.0391633 ]
 [-0.04834404  0.02487589 -0.04648942 -0.04920632  0.03282614 -0.04402144
  -0.04964077 -0.04768776  0.03593322  0.03410617]
 [ 0.04050321 -0.02292818 -0.04965336 -0.04762937 -0.03717884  0.03386403
   0.00699116 -0.04110593  0.00324805  0.04567892]
 [ 0.00218265  0.02167979  0.0496094   0.03917286  0.02352692 -0.01791175
  -0.0307554 